package com.househelper.resources;

import com.househelper.dto.ReassignmentTaskResponse;
import com.househelper.service.ReassignmentQueueService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import lombok.RequiredArgsConstructor;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;

@RestController
@RequestMapping("/api/reassignments")
@RequiredArgsConstructor
@Tag(name = "Reassignments", description = "Monitor and manage the emergency reassignment task queue.")
public class ReassignmentResource {

    private final ReassignmentQueueService reassignmentQueueService;

    @GetMapping("/tasks")
    @Operation(summary = "List reassignment tasks",
            description = "Returns all reassignment tasks generated by helper emergency cancellations, including their statuses and assigned substitute helpers.")
    public List<ReassignmentTaskResponse> getAllTasks() {
        return reassignmentQueueService.getAllTasks();
    }

    @PostMapping("/process")
    @Operation(summary = "Process pending reassignment tasks",
            description = "Triggers a check and execution across all pending reassignment queue messages, matching substitute maids or initiating fallback refunds.")
    public List<ReassignmentTaskResponse> processPendingTasks() {
        return reassignmentQueueService.processPendingTasks();
    }
}
